"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio         = [ 1, 4, 3 ]
sort_by       = "alphabetical"
sort_dir_first = true
show_hidden   = false
show_symlink  = true
scrolloff     = 5
title_format  = "Yazi: {cwd}"

[preview]
wrap       = "no"
tab_size   = 2
max_width  = 600
max_height = 900

[opener]
bat = [
	{ run = "bat --paging always %s", desc = "bat", for = "unix", block = true },
]
edit = [
	{ run = "${EDITOR:-vi} %s", desc = "$EDITOR", for = "unix", block = true },
]
open = [
	{ run = "xdg-open %s1", desc = "Open", for = "linux" },
]
reveal = [
	{ run = "xdg-open %d1", desc = "Reveal", for = "linux" },
]
extract = [
	{ run = "ya pub extract --list %s", desc = "Extract here" },
]

[open]
rules = [
	{ url = "*/",                use = [ "edit", "open", "reveal" ] },
	{ mime = "text/*",           use = [ "bat", "edit", "reveal" ] },
	{ mime = "image/*",          use = [ "open", "reveal" ] },
	{ mime = "{audio,video}/*",  use = [ "open", "reveal" ] },
	{ mime = "application/{json,ndjson}", use = [ "bat", "edit", "reveal" ] },
	{ mime = "*/javascript",     use = [ "bat", "edit", "reveal" ] },
	{ mime = "*",                use = [ "open", "reveal" ] },
]
